let cars=null;async function loadCars(){try{var e=await(await fetch("assets/car.json")).json();renderCars(cars=e.cars)}catch(e){console.error("Błąd podczas ładowania JSON:",e)}}loadCars();const filterSubmit=document.getElementById("filterSubmit"),carDetailsModal=document.getElementById("carDetailsModal"),modalTitle=carDetailsModal.querySelector(".modal-title"),modalPrice=carDetailsModal.querySelector("#modalPrice"),modalBody=carDetailsModal.querySelector(".modal-body"),modalCarVersion=carDetailsModal.querySelector("#version-group"),modalCarColor=carDetailsModal.querySelector("#color-group"),modalCarAccessories=carDetailsModal.querySelector("#accessories-group"),modalCarDesc=carDetailsModal.querySelector("#car-desc"),modalMainImg=carDetailsModal.querySelector(".modal-main-img"),modalThumbnailImg=carDetailsModal.querySelectorAll(".modal-thumbnail-img"),modalGallery=carDetailsModal.querySelector("#modalGallery"),modalPreviewRow=carDetailsModal.querySelector(".modal-preview-row"),modalFindDealer=carDetailsModal.querySelectorAll(".modalFindDealer");function formatPrice(e){return new Intl.NumberFormat("pl-PL",{style:"currency",currency:"PLN",minimumFractionDigits:0,maximumFractionDigits:0}).format(e)}function renderCars(e){const a=document.getElementById("carList");a.innerHTML="",e.length?e.forEach(e=>{a.innerHTML+=`
			<div class="col-md-4">
			<div class="card">
			<img src="assets/img/zx.png" class="card-img-top rounded-3 img-fluid" alt="Voltura ZX" style="display: block;">
			<div class="card-body p-3 p-md-2 p-lg-3">
			<p class="card__title">${e.model}</p>
			<p class="card__price mb-2 lh-1">od ${formatPrice(e.price)}</p>
			<div class="d-flex align-items-center justify-content-between">
			<p class="card__desc lh-1">AWD &bullet; ${e.range} km range</p>
			<button class="card__btn btn btn-blue px-3 py-1 rounded-4 fw-bold" data-bs-toggle="modal" data-bs-target="#carDetailsModal" data-car-id="${e.id}">Sprawdź</button>	  					
			</div>
			</div>
			</div>
			</div>
			`}):a.innerHTML+='<p class="fs-5 fw-bold text-center">Brak wyników</p>'}carDetailsModal.addEventListener("show.bs.modal",function(e){const a=e.relatedTarget.getAttribute("data-car-id");e=cars.find(e=>e.id==a);if(modalTitle.textContent=e.model+" — Szczegóły modelu",carDetailsModal.querySelector('input[name="car_name"]')?carDetailsModal.querySelector('input[name="car_name"]').value=e.model:((r=document.createElement("input")).type="hidden",r.name="car_name",r.value=e.model,modalBody.appendChild(r)),modalGallery.querySelector("#modalMainImg").innerHTML="",modalGallery.querySelector("#modalMainImg").innerHTML+=`<img src="assets/img/${e.images.main}" class="modal-main-img img-fluid rounded-3 mb-3" alt="${e.model}">`,e.images.additional.length){let a=modalGallery.querySelector(".modal-preview-row").innerHTML="";e.images.additional.forEach(function(e){a+=`<img src="assets/img/${e}" class="modal-thumbnail-img img-fluid rounded-2" alt="">`}),modalGallery.querySelector(".modal-preview-row").innerHTML=a}if(modalPrice.textContent=formatPrice(e.price),modalPrice.setAttribute("data-price",e.price),e.version.length){let a="";e.version.forEach(e=>{a+=`<button type="button" data-value="${e}" class="btn btn-transparent me-2 rounded-3">${e}</button>`}),modalCarVersion.querySelector(".btn-group").innerHTML=a}else modalCarVersion.style.display="none";var r=e.colors[0];if(Object.entries(r).length?(modalCarColor.querySelector(".btn-group").innerHTML="",Object.entries(r).forEach(([e,a])=>{e=`<button type="button" data-color-name="${e}" data-color-code="${a}" class="btn btn-transparent modal-btn-color  rounded-3 color-box" style="background-color: ${a}!important;"></button>`;modalCarColor.querySelector(".btn-group").innerHTML+=e})):modalCarColor.style.display="none",e.accessories_available&&Array.isArray(e.accessories_available)&&0<e.accessories_available.length){var l,t,o,c=e.accessories_available[0];carDetailsModal.querySelector("#accessories-group-row").innerHTML="";for([l,t]of Object.entries(c))c.hasOwnProperty(l)&&(o=`
				<label class="btn btn-transparent w-50" for="${l}">
				<input type="checkbox" class="btn-check hide" id="${l}" autocomplete="off">
				${t}
				</label>`,carDetailsModal.querySelector("#accessories-group-row").innerHTML+=o)}else carDetailsModal.querySelector("#accessories-group").style.display="none";modalCarAccessories.querySelectorAll(".btn-check").forEach(e=>{e.checked=!1});r=e.desc[0];Object.entries(r).length?(modalCarDesc.innerHTML="",Object.entries(r).forEach(([e,a])=>{let r="";"acceleration"==e?r="0–100 km/h":"top_speed"==e?r="Maksymalna prędkość":"charging"==e?r="Ładowanie":"boot_capacity"==e?r="Pojemność bagażnika":"warranty"==e&&(r="Gwarancja");e=`<div class="row mb-2">
			<p class="desc-label col-7 text-secondary">${r}</p>
			<p class="desc-val col-5 text-end">${a}</p>
			</div>`;modalCarDesc.innerHTML+=e})):modalCarDesc.style.display="none"}),carDetailsModal.querySelectorAll(".btn-group").forEach(a=>{a.addEventListener("click",e=>{e=e.target.closest("button");e&&(a.querySelectorAll("button").forEach(e=>e.classList.remove("active")),e.classList.add("active"))})}),modalPreviewRow.addEventListener("click",e=>{var a,r;e.target&&e.target.classList.contains("modal-thumbnail-img")&&(a=e.target,r=carDetailsModal.querySelector(".modal-main-img").src,carDetailsModal.querySelector(".modal-main-img").src=e.target.src,a.src=r,modalPreviewRow.appendChild(a))}),filterSubmit.addEventListener("click",e=>{e.preventDefault();const a=document.getElementById("filterType").value,r=document.getElementById("filterDrive").value,l=document.getElementById("filterPriceMin").value,t=document.getElementById("filterPriceMax").value;e=cars.filter(e=>!(a&&e.type!==a||(r&&e.drive!==r||l&&e.price<Number(l)||t&&e.price>Number(t))));a||r||l||t?renderCars(e):renderCars(cars)}),modalFindDealer.forEach(e=>{e.addEventListener("click",()=>{let a={};var e=carDetailsModal.querySelector("#version-group .btn.active"),r=carDetailsModal.querySelector("#color-group .btn.active");a.model=carDetailsModal.querySelector('input[name="car_name"]').value,e&&(a.version=e.getAttribute("data-value")),r&&(a.colorName=r.getAttribute("data-color-name"),a.colorCode=r.getAttribute("data-color-code")),carDetailsModal.querySelectorAll("#accessories-group-row input:checked").forEach(e=>{a[e.id]=1}),a.price=carDetailsModal.querySelector("#modalPrice").getAttribute("data-price"),localStorage.setItem("carModal",JSON.stringify(a)),bootstrap.Modal.getInstance(carDetailsModal).hide(),console.log(a)})});